import type { Metadata } from "next";
import { poppins, inter } from "@/styles/fonts";
import "./globals.css";
import TopBar from "@/components/layout/TopBar";
import FirstNavbar from "@/components/layout/FirstNavbar";
import SecondNavbar from "@/components/layout/SecondNavbar";
import Footer from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${poppins.variable} antialiased`}>
        <TopBar />
        <FirstNavbar />
        <SecondNavbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
